version: '3'
services:
  arangodb:
    image: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=root
    volumes:
      - "./data:/home"
      - "arango:/var/lib/arangodb3"
    ports:
      - 8529:8529
volumes:
  arango: